[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_THEME = "repo"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
