[build]
  publish = "public"
  command = "wget -O $HOME/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_Linux-64bit.tar.gz && tar xzf $HOME/hugo.tar.gz -C $HOME && mv $HOME/hugo $HOME/bin/ && $HOME/bin/hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.111.3"
  PATH = "/opt/build/repo/node_modules/.bin:/opt/build/repo/bin:${PATH}"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
