[build]
  publish = "public"
  command = "curl -L https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_linux-amd64.deb -o hugo.deb && sudo dpkg -i hugo.deb && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.111.3"
  GO_VERSION = "1.20"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
